name: Manual build
run-name: ${{ github.actor }} has started a build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test."
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls ${{ github.workspace }}