name: Manual release
run-name: ${{ github.actor }} has started a build to release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls -la ${{ github.workspace }}

      - run: zip -r ShrineOfSeparation.zip '${{ github.workspace }}/Data Files/'
      - run: zipinfo ShrineOfSeparation.zip

      # - name: Create Release and Upload
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: ShrineOfSeparation.zip