name: Manual release
run-name: ${{ github.actor }} has started a build to release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ls -la ${{ github.workspace }}

      - run: cd '${{ github.workspace }}/Data Files/' && zip -r ${{ github.workspace }}/ShrineOfSeparation.zip .
      - run: zipinfo ShrineOfSeparation.zip

      - name: Create Release and Upload
        uses: softprops/action-gh-release@v2
        with:
          files: ShrineOfSeparation.zip
